# Platform specific code goes here
obj-y	+= ce4100/
obj-y	+= efi/
obj-y	+= iris/
obj-y	+= olpc/
obj-y	+= scx200/
obj-y	+= sfi/
obj-y	+= visws/
obj-y	+= uv/
obj-$(CONFIG_X86_MRST)	+= mrst/
obj-$(CONFIG_X86_MDFLD)	+= mdfld/
